<script setup lang="ts">
import { ref, nextTick, onMounted, computed, watch } from 'vue';
import { useConversationsStore } from '@/stores/conversationsStore';
import type { Conversation } from '@/types';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import {
  Sparkles, Plus, Clock, MoreVertical,
  Send, Download, MessageCircle, X, Pencil, Trash2
} from 'lucide-vue-next';

const store = useConversationsStore();
const input = ref('');
const bottomRef = ref<HTMLDivElement | null>(null);
const sentinelRef = ref<HTMLDivElement | null>(null);
const historyOpen = ref(false);

// Context menu state
const ctxMenu = ref<{ conv: Conversation; x: number; y: number } | null>(null);
const renameDialog = ref<{ conv: Conversation; value: string } | null>(null);
const deleteDialog = ref<Conversation | null>(null);

const messages = computed(() => store.messages);
const loading = computed(() => store.isLoading);
const sending = computed(() => store.isSending);
const conversations = computed(() => store.conversations);
const activeSessionId = computed(() => store.activeSessionId);
const chatHasMore = computed(() => store.chatHasMore);

const renderMarkdown = (text: string) => {
  try {
    return DOMPurify.sanitize(marked.parse(text) as string);
  } catch {
    return DOMPurify.sanitize(text);
  }
};

const scrollToBottom = async (behavior: ScrollBehavior = 'smooth') => {
  await nextTick();
  bottomRef.value?.scrollIntoView({ behavior });
};

watch([() => messages.value.length, sending, loading], () => {
  scrollToBottom();
});

onMounted(async () => {
  await store.fetchConversations();
  if (!store.activeSessionId && store.conversations.length > 0) {
    await store.selectConversation(store.conversations[0].id);
  }
  await nextTick();
  setTimeout(() => scrollToBottom('auto'), 100);

  // IntersectionObserver for infinite scroll (load older messages)
  if (sentinelRef.value) {
    const obs = new IntersectionObserver((entries) => {
      if (entries[0].isIntersecting && chatHasMore.value && !loading.value) {
        store.loadMoreMessages();
      }
    }, { threshold: 0.1 });
    obs.observe(sentinelRef.value);
  }

  // Close ctx menu on outside click
  document.addEventListener('click', closeCtxMenu);
});

async function handleSend() {
  if (!input.value.trim() || sending.value) return;
  const text = input.value;
  input.value = '';
  await store.sendMessage(text);
}

async function createNew() {
  await store.createConversation('Nueva conversación');
  input.value = '';
  historyOpen.value = false;
}

async function selectSession(id: string) {
  await store.selectConversation(id);
  historyOpen.value = false;
}

function showOptions(e: MouseEvent, conv: Conversation) {
  e.stopPropagation();
  ctxMenu.value = { conv, x: e.clientX, y: e.clientY };
}

function closeCtxMenu() {
  ctxMenu.value = null;
}

function startRename() {
  if (!ctxMenu.value) return;
  renameDialog.value = { conv: ctxMenu.value.conv, value: ctxMenu.value.conv.title };
  ctxMenu.value = null;
}

function startDelete() {
  if (!ctxMenu.value) return;
  deleteDialog.value = ctxMenu.value.conv;
  ctxMenu.value = null;
}

async function confirmRename() {
  if (!renameDialog.value || !renameDialog.value.value.trim()) return;
  await store.renameConversation(renameDialog.value.conv.id, renameDialog.value.value);
  renameDialog.value = null;
}

async function confirmDelete() {
  if (!deleteDialog.value) return;
  await store.deleteConversation(deleteDialog.value.id);
  deleteDialog.value = null;
}

const formatDate = (dateStr: string) =>
  new Date(dateStr).toLocaleDateString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });

function printMessage(msgId: string) {
  const el = document.getElementById(`msg-${msgId}`);
  if (!el) return;
  const pw = window.open('', '_blank');
  if (!pw) return;
  pw.document.write(`
    <html>
      <head><title>AgroNexus AI Report</title>
      <style>
        body{font-family:sans-serif;padding:40px;color:#333}
        h2{color:#10b981}
        table{width:100%;border-collapse:collapse;margin-bottom:20px}
        th{background:#10b981;color:white;padding:10px;text-align:left}
        td{border:1px solid #eee;padding:10px}
        .meta{font-size:12px;color:#888;margin-top:20px;text-align:center;border-top:1px solid #eee;padding-top:20px}
      </style></head>
      <body>${el.innerHTML}
        <div class="meta">Generated by AgroNexus AI on ${new Date().toLocaleString()}</div>
      </body></html>`);
  pw.document.close();
  pw.print();
  pw.close();
}
</script>

<template>
  <div class="chat-shell">

    <!-- Main chat area -->
    <div class="chat-main">
      <!-- Toolbar -->
      <div class="chat-toolbar">
        <div class="ag-flex-row gap-2">
          <button id="history-toggle-btn" class="icon-btn text-primary" @click="historyOpen = true" title="Chat history">
            <Clock :size="18" />
          </button>
        </div>
        <div class="toolbar-center">
          <span v-if="activeSessionId" class="session-name">
            {{ conversations.find(c => c.id === activeSessionId)?.title || 'Chat' }}
          </span>
          <span v-else class="app-name ag-text-gradient">AgroNexus AI</span>
        </div>
        <button id="new-chat-top-btn" class="new-btn hide-on-mobile" @click="createNew">
          <Plus :size="16" />
          <span>Nuevo</span>
        </button>
      </div>

      <!-- Messages area -->
      <div class="chat-scroll" id="chat-messages-area">
        <div class="chat-container">
          <!-- Welcome -->
          <div v-if="messages.length === 0 && !loading" class="welcome-container">
            <div class="welcome-icon">
              <Sparkles :size="32" class="text-primary" />
            </div>
            <h1>Hi, I'm AgroNexus</h1>
            <p>Your personal agricultural assistant. Ask about telemetry, system health, or crop recommendations.</p>
          </div>

          <!-- Infinite scroll sentinel (at top) -->
          <div ref="sentinelRef" class="scroll-sentinel-top" />

          <!-- Messages -->
          <div v-for="msg in messages" :key="msg.id" class="message-wrapper" :class="msg.role" :id="`msg-${msg.id}`">
            <div class="message-bubble">
              <div class="markdown-body" v-html="renderMarkdown(msg.message)" />
            </div>
            <div class="message-meta">
              <span>{{ msg.role === 'user' ? 'You' : 'AgroNexus' }} · {{ new Date(msg.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }}</span>
              <button v-if="msg.role === 'ai'" class="dl-btn no-print" @click="printMessage(msg.id)" title="Export">
                <Download :size="13" />
              </button>
            </div>
          </div>

          <!-- Typing indicator -->
          <div v-if="loading || sending" class="message-wrapper ai">
            <div class="message-bubble typing-bubble">
              <div class="typing-indicator">
                <span /><span /><span />
              </div>
            </div>
          </div>

          <div ref="bottomRef" class="scroll-anchor" />
        </div>
      </div>

      <!-- Input footer -->
      <div class="chat-footer">
        <div class="input-container">
          <div class="input-card">
            <input
              id="chat-input"
              v-model="input"
              type="text"
              placeholder="Ask AgroNexus..."
              class="chat-input"
              :disabled="sending"
              @keyup.enter="handleSend"
            />
            <button
              id="chat-send-btn"
              class="send-btn"
              @click="handleSend"
              :disabled="sending || !input.trim()"
            >
              <div class="send-icon-box" :class="{ active: input.trim() && !sending }">
                <Send :size="18" />
              </div>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Mobile History Drawer -->
    <Teleport to="body">
      <Transition name="drawer">
        <div v-if="historyOpen" class="drawer-overlay" @click="historyOpen = false">
          <div class="history-drawer" @click.stop>
            <div class="drawer-header">
              <span class="drawer-title">Historial de Chat</span>
              <button class="icon-btn" @click="historyOpen = false"><X :size="18" /></button>
            </div>
            <button class="mobile-new-btn" @click="createNew">
              <Plus :size="16" /> Nueva conversación
            </button>
            <div class="drawer-list">
              <div
                v-for="conv in conversations"
                :key="conv.id"
                class="conv-item"
                :class="{ 'is-active': conv.id === activeSessionId }"
                @click="selectSession(conv.id)"
              >
                <div class="conv-item-info">
                  <span class="conv-title">{{ conv.title }}</span>
                  <span class="conv-date">{{ formatDate(conv.updated_at) }}</span>
                </div>
                <button class="conv-opts-btn" @click="showOptions($event, conv)"><MoreVertical :size="15" /></button>
              </div>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>

    <!-- Context Menu -->
    <Teleport to="body">
      <div
        v-if="ctxMenu"
        class="ctx-menu"
        :style="{ top: `${ctxMenu.y}px`, left: `${ctxMenu.x}px` }"
        @click.stop
      >
        <button class="ctx-item" @click="startRename"><Pencil :size="14" /> Renombrar</button>
        <button class="ctx-item danger" @click="startDelete"><Trash2 :size="14" /> Eliminar</button>
      </div>
    </Teleport>

    <!-- Rename Dialog -->
    <Teleport to="body">
      <div v-if="renameDialog" class="dialog-backdrop" @click="renameDialog = null">
        <div class="dialog-box" @click.stop>
          <h3>Renombrar conversación</h3>
          <input
            id="rename-input"
            v-model="renameDialog.value"
            type="text"
            class="dialog-input"
            placeholder="Nuevo nombre"
            @keyup.enter="confirmRename"
          />
          <div class="dialog-actions">
            <button class="dialog-cancel" @click="renameDialog = null">Cancelar</button>
            <button class="dialog-confirm" @click="confirmRename">Guardar</button>
          </div>
        </div>
      </div>
    </Teleport>

    <!-- Delete Confirm Dialog -->
    <Teleport to="body">
      <div v-if="deleteDialog" class="dialog-backdrop" @click="deleteDialog = null">
        <div class="dialog-box" @click.stop>
          <h3>¿Eliminar conversación?</h3>
          <p class="dialog-desc">Esta acción no se puede deshacer. Se borrará "{{ deleteDialog.title }}".</p>
          <div class="dialog-actions">
            <button class="dialog-cancel" @click="deleteDialog = null">Cancelar</button>
            <button class="dialog-confirm danger" @click="confirmDelete">Eliminar</button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<style scoped>
.chat-shell {
  display: flex;
  height: 100%;
  overflow: hidden;
  background: var(--ag-bg);
}

/* ── Main chat ── */
.chat-main {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-width: 0;
  overflow: hidden;
}

/* ─ Toolbar ─ */
.chat-toolbar {
  display: flex;
  align-items: center;
  padding: 0.75rem 1rem;
  background: var(--ag-bg);
  border-bottom: 1px solid var(--ag-border);
  flex-shrink: 0;
  gap: 0.75rem;
}

.toolbar-center {
  flex: 1;
  text-align: center;
}

.session-name {
  font-size: 0.9rem;
  font-weight: 700;
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.app-name {
  font-size: 1rem;
  font-weight: 800;
}

.icon-btn {
  background: transparent;
  border: none;
  color: var(--ag-text-muted);
  cursor: pointer;
  padding: 0.375rem;
  border-radius: 8px;
  display: flex;
  align-items: center;
  transition: all 0.2s;
}

.icon-btn:hover { background: var(--ag-card); color: var(--ag-text); }

.new-btn {
  display: flex;
  align-items: center;
  gap: 0.35rem;
  background: rgba(var(--ag-primary-rgb), 0.1);
  border: 1px solid rgba(var(--ag-primary-rgb), 0.2);
  border-radius: 8px;
  color: var(--ag-primary);
  font-size: 0.8rem;
  font-weight: 700;
  font-family: var(--ag-font);
  padding: 0.4rem 0.875rem;
  cursor: pointer;
  transition: all 0.2s;
}

.new-btn:hover { background: rgba(var(--ag-primary-rgb), 0.18); }

/* ─ Chat scroll ─ */
.chat-scroll {
  flex: 1;
  overflow-y: auto;
  background: var(--ag-bg);
}

.chat-container {
  max-width: 780px;
  margin: 0 auto;
  padding: 1.5rem 1rem 2rem;
}

.scroll-sentinel-top { height: 1px; }
.scroll-anchor { height: 1px; }

/* ─ Welcome ─ */
.welcome-container {
  text-align: center;
  padding: 4rem 2rem;
  max-width: 480px;
  margin: 0 auto;
}

.welcome-icon {
  width: 72px;
  height: 72px;
  background: rgba(var(--ag-primary-rgb), 0.1);
  border-radius: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 1.5rem;
}

.welcome-container h1 {
  font-size: 1.875rem;
  font-weight: 800;
  margin: 0 0 0.75rem;
  letter-spacing: -0.03em;
}

.welcome-container p {
  color: var(--ag-text-muted);
  line-height: 1.6;
}

/* ─ Messages ─ */
.message-wrapper {
  display: flex;
  flex-direction: column;
  margin-bottom: 1rem;
  max-width: 80%;
}

.message-wrapper.user {
  align-self: flex-end;
  margin-left: auto;
}

.message-wrapper.ai {
  align-self: flex-start;
  margin-right: auto;
}

.message-bubble {
  border-radius: 18px;
  padding: 0.875rem 1.125rem;
  font-size: 0.9rem;
  line-height: 1.6;
}

.message-wrapper.user .message-bubble {
  background: rgba(var(--ag-primary-rgb), 0.15);
  border: 1px solid rgba(var(--ag-primary-rgb), 0.25);
  border-bottom-right-radius: 4px;
}

.message-wrapper.ai .message-bubble {
  background: var(--ag-card);
  border: 1px solid var(--ag-border);
  border-bottom-left-radius: 4px;
}

.message-meta {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 0.68rem;
  color: var(--ag-text-muted);
  margin-top: 0.3rem;
  padding: 0 0.25rem;
}

.dl-btn {
  background: transparent;
  border: none;
  color: var(--ag-text-muted);
  cursor: pointer;
  padding: 0.2rem;
  display: flex;
  align-items: center;
  border-radius: 4px;
  transition: all 0.2s;
}

.dl-btn:hover { color: var(--ag-primary); }

/* ─ Typing ─ */
.typing-bubble { padding: 0.875rem 1.125rem; }

.typing-indicator {
  display: flex;
  align-items: center;
  gap: 4px;
  height: 16px;
}

.typing-indicator span {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--ag-primary);
  animation: bounce 1.2s ease infinite;
}

.typing-indicator span:nth-child(2) { animation-delay: 0.2s; }
.typing-indicator span:nth-child(3) { animation-delay: 0.4s; }

@keyframes bounce {
  0%, 100% { transform: translateY(0); opacity: 0.5; }
  50% { transform: translateY(-5px); opacity: 1; }
}

/* ─ Input footer ─ */
.chat-footer {
  padding: 0.75rem 1rem;
  background: var(--ag-bg);
  border-top: 1px solid var(--ag-border);
  flex-shrink: 0;
}

.input-container { max-width: 780px; margin: 0 auto; }

.input-card {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  background: var(--ag-card);
  border: 1px solid var(--ag-border);
  border-radius: 16px;
  padding: 0.25rem 0.25rem 0.25rem 1rem;
  transition: border-color 0.2s;
}

.input-card:focus-within { border-color: rgba(var(--ag-primary-rgb), 0.4); }

.chat-input {
  flex: 1;
  background: transparent;
  border: none;
  color: var(--ag-text);
  font-size: 0.9rem;
  font-family: var(--ag-font);
  outline: none;
  padding: 0.5rem 0;
}

.chat-input::placeholder { color: var(--ag-text-muted); }
.chat-input:disabled { opacity: 0.5; }

.send-btn {
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 0;
  flex-shrink: 0;
}

.send-btn:disabled { cursor: not-allowed; }

.send-icon-box {
  width: 42px;
  height: 42px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(255,255,255,0.05);
  color: var(--ag-text-muted);
  transition: all 0.2s ease;
}

.send-icon-box.active {
  background: var(--ag-primary);
  color: white;
  box-shadow: 0 4px 12px rgba(var(--ag-primary-rgb), 0.3);
}

/* ─ Mobile drawer ─ */
.drawer-overlay {
  position: fixed;
  inset: 0;
  z-index: 2000;
  background: rgba(0,0,0,0.7);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
}

.history-drawer {
  width: 100%;
  max-width: 400px;
  max-height: 80vh;
  background: var(--ag-card);
  border-radius: 24px;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.drawer-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1.25rem 1.5rem;
  border-bottom: 1px solid var(--ag-border);
  flex-shrink: 0;
}

.drawer-title {
  font-size: 0.875rem;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.mobile-new-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  width: calc(100% - 3rem);
  margin: 1rem 1.5rem 0.5rem;
  padding: 0.75rem 1rem;
  background: var(--ag-bg);
  border: 1px solid var(--ag-border);
  border-radius: 12px;
  color: var(--ag-text);
  font-weight: 600;
  font-family: var(--ag-font);
  cursor: pointer;
}

.drawer-list { flex: 1; overflow-y: auto; padding: 0.5rem 1rem 2rem; }

.conv-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem;
  border-radius: 10px;
  cursor: pointer;
  transition: background 0.15s ease;
  margin-bottom: 2px;
}

.conv-item:hover { background: rgba(255,255,255,0.04); }
.conv-item.is-active { background: rgba(var(--ag-primary-rgb), 0.08); border: 1px solid rgba(var(--ag-primary-rgb), 0.15); }

.conv-item-info { flex: 1; min-width: 0; }
.conv-title {
  display: block;
  font-size: 0.85rem;
  font-weight: 600;
  color: var(--ag-text);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.conv-date {
  display: block;
  font-size: 0.7rem;
  color: var(--ag-text-muted);
  margin-top: 2px;
}

.conv-opts-btn {
  background: transparent;
  border: none;
  color: var(--ag-text-muted);
  cursor: pointer;
  padding: 0.25rem;
  border-radius: 6px;
  display: flex;
  align-items: center;
  flex-shrink: 0;
  opacity: 0.5;
  transition: all 0.15s;
}

.conv-item:hover .conv-opts-btn { opacity: 1; }
.conv-opts-btn:hover { background: rgba(255,255,255,0.08); color: var(--ag-text); }

/* ─ Context Menu ─ */
.ctx-menu {
  position: fixed;
  z-index: 5000;
  background: var(--ag-card);
  border: 1px solid var(--ag-border);
  border-radius: 12px;
  box-shadow: 0 16px 40px rgba(0,0,0,0.5);
  overflow: hidden;
  min-width: 150px;
}

.ctx-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  width: 100%;
  padding: 0.75rem 1rem;
  background: transparent;
  border: none;
  color: var(--ag-text);
  font-size: 0.875rem;
  font-family: var(--ag-font);
  cursor: pointer;
  text-align: left;
  transition: background 0.15s;
}

.ctx-item:hover { background: rgba(255,255,255,0.06); }
.ctx-item.danger { color: var(--ag-red); }
.ctx-item.danger:hover { background: rgba(239,68,68,0.08); }

/* ─ Dialogs ─ */
.dialog-backdrop {
  position: fixed;
  inset: 0;
  z-index: 4000;
  background: rgba(0,0,0,0.75);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
  backdrop-filter: blur(4px);
}

.dialog-box {
  background: var(--ag-card);
  border: 1px solid var(--ag-border);
  border-radius: 20px;
  padding: 1.75rem;
  width: 100%;
  max-width: 380px;
  box-shadow: 0 24px 60px rgba(0,0,0,0.5);
}

.dialog-box h3 { margin: 0 0 1.25rem; font-size: 1.1rem; font-weight: 700; }

.dialog-desc { font-size: 0.875rem; color: var(--ag-text-muted); margin: 0 0 1.25rem; }

.dialog-input {
  width: 100%;
  padding: 0.75rem 1rem;
  background: rgba(255,255,255,0.04);
  border: 1px solid var(--ag-border);
  border-radius: 10px;
  color: var(--ag-text);
  font-family: var(--ag-font);
  font-size: 0.9rem;
  outline: none;
  margin-bottom: 1.25rem;
}

.dialog-input:focus { border-color: var(--ag-primary); }

.dialog-actions { display: flex; justify-content: flex-end; gap: 0.75rem; }

.dialog-cancel {
  background: transparent;
  border: 1px solid var(--ag-border);
  border-radius: 10px;
  color: var(--ag-text-muted);
  padding: 0.625rem 1.25rem;
  font-family: var(--ag-font);
  font-weight: 600;
  cursor: pointer;
}

.dialog-confirm {
  background: var(--ag-primary);
  border: none;
  border-radius: 10px;
  color: white;
  padding: 0.625rem 1.25rem;
  font-family: var(--ag-font);
  font-weight: 700;
  cursor: pointer;
}

.dialog-confirm.danger { background: var(--ag-red); }

/* ─ Transitions ─ */
.drawer-enter-active, .drawer-leave-active { transition: opacity 0.25s; }
.drawer-enter-active .history-drawer, .drawer-leave-active .history-drawer { transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1) scale 0.3s; }
.drawer-enter-from, .drawer-leave-to { opacity: 0; }
.drawer-enter-from .history-drawer, .drawer-leave-to .history-drawer { transform: translateY(20px) scale(0.95); opacity: 0; }

/* ─ Markdown body ─ */
.markdown-body { color: var(--ag-text); line-height: 1.6; font-size: 0.9rem; }
.markdown-body :deep(h1), .markdown-body :deep(h2), .markdown-body :deep(h3) {
  color: #fff; font-weight: 800; margin: 1.5rem 0 0.75rem; letter-spacing: -0.02em;
}
.markdown-body :deep(h2) { font-size: 1.3rem; color: var(--ag-primary); }
.markdown-body :deep(p) { margin-bottom: 0.875rem; }
.markdown-body :deep(ul), .markdown-body :deep(ol) { margin-bottom: 1rem; padding-left: 1.25rem; }
.markdown-body :deep(li) { margin-bottom: 0.35rem; }
.markdown-body :deep(code) {
  background: rgba(0,0,0,0.3); padding: 0.15rem 0.35rem; border-radius: 4px;
  font-family: 'JetBrains Mono', monospace; font-size: 0.85em;
}
.markdown-body :deep(pre) {
  background: rgba(0,0,0,0.3); border: 1px solid var(--ag-border);
  border-radius: 10px; padding: 1rem; overflow-x: auto; margin-bottom: 1rem;
}
.markdown-body :deep(pre code) { background: none; padding: 0; }
.markdown-body :deep(table) {
  width: 100%; border-collapse: separate; border-spacing: 0; margin-bottom: 1.5rem;
  background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.05);
  border-radius: 10px; overflow: hidden;
}
.markdown-body :deep(th) {
  background: rgba(var(--ag-primary-rgb), 0.1); color: var(--ag-primary);
  font-weight: 700; padding: 0.625rem 1rem; font-size: 0.8rem; text-transform: uppercase;
}
.markdown-body :deep(td) { padding: 0.625rem 1rem; border-top: 1px solid rgba(255,255,255,0.05); font-size: 0.85rem; }
.markdown-body :deep(blockquote) {
  margin: 1rem 0; padding: 0.875rem 1.25rem; background: rgba(255,255,255,0.03);
  border-left: 3px solid var(--ag-primary); border-radius: 0 8px 8px 0;
}
.markdown-body :deep(strong) { color: #fff; }
</style>
